### ISSUE TITLE
As a team member, I want a document that highlights any open issues or outlines the plan for the next sprint, so that we can address them and plan accordingly.

### ISSUE THREAD

**Issue by PrashantBanavali** [saurabhs679/AgileMinds-Soen6011summer2023#14]
Highlight open issues, planned discussion for tasks to be undertaken as part of Sprint-2

**Comment by SrikarHasthi** [comment]
The project is progressing smoothly, and all milestones and tasks are being completed as scheduled.  There are no open issues.

**Comment by SrikarHasthi** [comment]
For the next sprint, Sprint 2 Task Board has been created and the team will select the user stories based on the priority.
