### ISSUE TITLE
As a job seeker/candidate, I want to upload my resume and relevant documents, So that I can submit them for my job application.

### ISSUE THREAD

**Issue by SrikarHasthi** [saurabhs679/AgileMinds-Soen6011summer2023#57]
**Priority** : Medium 
**Story Points** :  5

**Acceptance Criteria** : 
Given that I am on the job application page, when I click on the "Upload Resume" button, then I should be able to select and upload my resume file. And the system should display a success message confirming the upload

**Comment by srikarvishnudatta** [comment]
Task completed
