### ISSUE TITLE
As an employer, I want to view the required documents uploaded by the job seekers or candidates, So that I can find suitable candidates for our job openings. 

### ISSUE THREAD

**Issue by SrikarHasthi** [saurabhs679/AgileMinds-Soen6011summer2023#59]
**Priority** : Medium
**Story Points** :  3

**Acceptance Criteria** : 
Given that I am reviewing a candidate’s application, when I access the candidate’s file, then I should be able to view and download the suitable candidate’s documents and continue the hiring process.

**Comment by Madhava5** [comment]
The upload feature has been done
