### ISSUE TITLE
Create a job posting form

### ISSUE THREAD

**Issue by srikarvishnudatta** [saurabhs679/AgileMinds-Soen6011summer2023#66]
Related to #59 

- Develop a user-friendly form where employers can input job details such as job title, description, responsibilities, qualifications, experience level, location, and application deadline.
- Include validation checks to ensure that all required fields are filled and that the entered information meets the specified criteria.

**Comment by saurabhs679** [comment]
Work in progress for the employer Job post feature.

**Comment by PrashantBanavali** [comment]
The task has been completed hence closing it for the sprint.
